version: '3'

services:
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://database_fullcycle:3306 -timeout 20s docker-entrypoint.sh 
    networks:
      - node-challenge
    command: node index.js
    tty: true
    depends_on:
      - database_fullcycle
    

  database_fullcycle:
    image: mysql:5.7.42
    command: --innodb-use-native-aio=0
    container_name: database_fullcycle
    restart: always
    tty: true
    volumes:
      - ./mysql/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle-node-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-challenge

  proxy:
    container_name: proxy
    build:
      context: ./nginx
    image: alysonrode/node-challenge-proxy
    tty: true
    restart: always
    ports:
      - '8080:80'
    networks:
      - node-challenge

networks:
  node-challenge:
    driver: bridge